-- liquibase formatted sql

-- changeset a.hage:1713397988380-4
ALTER TABLE book DROP CONSTRAINT fk_book_on_member;

-- changeset a.hage:1713397988380-1
CREATE TABLE member_book
(
    id        INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    member_id INTEGER,
    book_id   INTEGER,
    CONSTRAINT pk_memberbook PRIMARY KEY (id)
);

-- changeset a.hage:1713397988380-2
ALTER TABLE member_book
    ADD CONSTRAINT FK_MEMBERBOOK_ON_BOOK FOREIGN KEY (book_id) REFERENCES book (id);

-- changeset a.hage:1713397988380-3
ALTER TABLE member_book
    ADD CONSTRAINT FK_MEMBERBOOK_ON_MEMBER FOREIGN KEY (member_id) REFERENCES member (id);

-- changeset a.hage:1713397988380-5
ALTER TABLE book DROP COLUMN member_id;

